module.exports = {
  policies: {
    "Which hospitals post a Finacial Assistance Policy online, outlining which patients qualify for help with their bills and how they can get aid?": "FAP",
    "Which hospitals post their collection policies online, explaining what tactics they use to collect bills and what can happen to patients who don't pay?": "COLLECTIONS",
    "Which hospitals will report patients who don't pay their bills to credit reporting agencies?": "REPORTED",
    "Which hospitals will sell patients' debts to third-party buyers, who can then pursue patients to collect?": "DEBT",
    "Which hospitals will sue patients or take other legal actions to collect bills, such as garnishing wages or placing liens on patients' property?": "SUED",
    "Which hospitals will deny non-emergency medical care to patients with past-due bills?": "DENIED",
    "Info on financial assistance available with 'financial assistance' search?" : "FINASSIST",
    "Medicaid expansion?": "MEDICAID",
    "Places liens or garnishes wages?": "LIENS",
    "Qualifying income for discounted care?": "DISCOUNTED",
    "Scorecard notes": "SCORECARD",
    "CITY": "CITY",
    "fips": "fips",
    "HOSPITAL_TYPE": "HOSPITAL_TYPE",
    "STATE": "state",
    "SYSTEM": "SYSTEM",
    "NAME": "NAME",
  },

  //come up with an array of arrays that hold colors that you want to use for the key, one group of colors for each policy
  colors: {
    "DEBT": ['#883006', '#DCDCDC', '#D1AE9A'],
    "FAP": ['#052962', '#DCDCDC', '#94A0B3'],
    "COLLECTIONS": ['#588A5A', '#DCDCDC', '#9AB39B'],
    "REPORTED": ['#FFBB50', '#DCDCDC', '#E7D1AD'],
    "SUED": ['#4C0688', '#DCDCDC', '#BCABCD'],
    "DENIED": ['#880366', '#DCDCDC', '#D19ABD'],
  },
  listOfArrays: [["state"], 
    ["HOSPITAL_TYPE"],
    ["FAP"], 
    ["COLLECTIONS"], 
    ["REPORTED"], 
    ["DEBT"], 
    ["SUED"], 
    ["DENIED"]],
  radarChart: {
    "DEBT": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "FAP": "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "COLLECTIONS": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
    "REPORTED": "mo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.",
    "SUED": "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem",
    "DENIED": "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos.",
    "DISCOUNTED": "lorem ipsum"
  },
  
  states: {
    "Filter by state": "All",
    arizona: "AZ",
    alabama: "AL",
    alaska: "AK",
    arkansas: "AR",
    california: "CA",
    colorado: "CO",
    connecticut: "CT",
    "district of columbia": "DC",
    delaware: "DE",
    florida: "FL",
    georgia: "GA",
    hawaii: "HI",
    idaho: "ID",
    illinois: "IL",
    indiana: "IN",
    iowa: "IA",
    kansas: "KS",
    kentucky: "KY",
    louisiana: "LA",
    maine: "ME",
    maryland: "MD",
    massachusetts: "MA",
    michigan: "MI",
    minnesota: "MN",
    mississippi: "MS",
    missouri: "MO",
    montana: "MT",
    nebraska: "NE",
    nevada: "NV",
    "new hampshire": "NH",
    "new jersey": "NJ",
    "new mexico": "NM",
    "new york": "NY",
    "north carolina": "NC",
    "north dakota": "ND",
    ohio: "OH",
    oklahoma: "OK",
    oregon: "OR",
    pennsylvania: "PA",
    "rhode island": "RI",
    "south carolina": "SC",
    "south dakota": "SD",
    tennessee: "TN",
    texas: "TX",
    utah: "UT",
    vermont: "VT",
    virginia: "VA",
    washington: "WA",
    "west virginia": "WV",
    wisconsin: "WI",
    wyoming: "WY",
    "american samoa": "AS",
    guam: "GU",
    "northern mariana islands": "MP",
    "puerto rico": "PR",
    "us virgin islands": "VI",
    "us minor outlying islands": "UM",
  }
};