module.exports = {
    policies: {
        "Financial Assistance Policy available online?": "FAP",
        "Collections policies available online?": "COLLECTIONS",
        "Patients can be reported to credit bureaus?": "REPORTED",
        "Patients' debts can be sold?": "DEBT",
        "Patients can be sued or subject to wage garnishment or property liens?": "SUED",
        "colPatients with debt can be denied non-emergency care?orado": "DENIED"
      },
    states: {
        "Filter by state": "All",
        arizona: "AZ",
        alabama: "AL",
        alaska: "AK",
        arkansas: "AR",
        california: "CA",
        colorado: "CO",
        connecticut: "CT",
        "district of columbia": "DC",
        delaware: "DE",
        florida: "FL",
        georgia: "GA",
        hawaii: "HI",
        idaho: "ID",
        illinois: "IL",
        indiana: "IN",
        iowa: "IA",
        kansas: "KS",
        kentucky: "KY",
        louisiana: "LA",
        maine: "ME",
        maryland: "MD",
        massachusetts: "MA",
        michigan: "MI",
        minnesota: "MN",
        mississippi: "MS",
        missouri: "MO",
        montana: "MT",
        nebraska: "NE",
        nevada: "NV",
        "new hampshire": "NH",
        "new jersey": "NJ",
        "new mexico": "NM",
        "new york": "NY",
        "north carolina": "NC",
        "north dakota": "ND",
        ohio: "OH",
        oklahoma: "OK",
        oregon: "OR",
        pennsylvania: "PA",
        "rhode island": "RI",
        "south carolina": "SC",
        "south dakota": "SD",
        tennessee: "TN",
        texas: "TX",
        utah: "UT",
        vermont: "VT",
        virginia: "VA",
        washington: "WA",
        "west virginia": "WV",
        wisconsin: "WI",
        wyoming: "WY",
        "american samoa": "AS",
        guam: "GU",
        "northern mariana islands": "MP",
        "puerto rico": "PR",
        "us virgin islands": "VI",
        "us minor outlying islands": "UM",
      }
  };